name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: xolider
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    
    - name: Docker build and push
      uses: docker/build-push-action@v3.2.0
      with:
        no-cache: true
        tags: xolider/fastshare-api
        push: true

  deploy:
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
    - name: SSH deploy
      uses: Flaavius/ssh-commands@1.0
      with:
        username: ${{ secrets.SSH_USER }}
        host: ${{ secrets.SSH_HOST }}
        password: ${{ secrets.SSH_PASSWORD }}
        command: sh ~/fastshare/deploy.sh
    
  publish-javadoc:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup JDK 11
      uses: actions/setup-java@v3.6.0
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run publish HTML
      run: chmod +x ./gradlew && ./gradlew dokkaHtml
        
